aigateway:
  baseurl: http://localhost:8080/chat/completions
  models:
    # 用于并行调用的模型列表
    generation:
      - doubao
      - qwen
    # 用于评分的模型
    scorer: deepseek
server:
  address: 0.0.0.0
  port: 8081

# Swagger配置 - 生产环境部署时，取消下面的注释并设置正确的URL
swagger:
  server:
    url: http://47.100.171.209:8081
